steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}",
        "${_SERVICE_FOLDER}",
      ]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]
    
  - id: terraform-init
    name: hashicorp/terraform:0.14.8
    args:
      - 'init'
      - '-no-color'
      - '-input=false'
      - './'

  - id: terraform-plan
    name: hashicorp/terraform:0.14.8
    args:
      - 'plan'
      - '-no-color'
      - '-input=false'
      - './'
 
   - id: terraform-apply
     name: hashicorp/terraform:0.14.8
     args:
      - 'apply'
      - '-auto-approve'
      - '-no-color'
      - '-input=false'
      - './'

substitutions:
  _SERVICE_FOLDER: service
  _SERVICE_NAME: cats

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"
  
options:
  logging: CLOUD_LOGGING_ONLY  
